allowBuilds:
  '@google/genai': false
  esbuild: true
  node-pty: true
  protobufjs: false
cacheDir: .cache/pnpm-cache
engineStrict: true
savePrefix: ''
storeDir: .cache/pnpm-store
verifyDepsBeforeRun: false
