import type { SharedScenarioSeed } from "../src/pack-builder.js";

export const developmentScenarioSeeds: readonly SharedScenarioSeed[] = Object.freeze([
  Object.freeze({
    familyId: "atlas-locale-fallback",
    parentTaskDomain: "localization",
    subjectEn: "Atlas desktop localization",
    subjectZh: "Atlas 桌面端本地化",
    stableKeyEn: "catalog load order",
    stableKeyZh: "语言目录加载顺序",
    stableValue: "core-before-plugins",
    settingNameEn: "fallback locale",
    settingNameZh: "回退语言",
    oldValue: "en-US",
    currentValue: "en-GB",
    companionNameEn: "missing-key behavior",
    companionNameZh: "缺失键处理",
    companionValue: "show-source-key",
    toolOutcomeEn: "the offline locale audit passed 48 of 48 catalog checks",
    toolOutcomeZh: "离线语言审计的 48 项目录检查全部通过",
    workflowEn: "load the core catalog, then plugin catalogs, then run the offline locale audit",
    workflowZh: "先加载核心目录，再加载插件目录，最后执行离线语言审计",
    gotchaEn: "Plugin strings must never replace a core security warning.",
    gotchaZh: "插件文案不能覆盖核心安全警告",
    absentFieldEn: "emergency translation owner",
    absentFieldZh: "紧急翻译负责人",
    filteredValue: "contractor-lime",
    artifactRef: "artifacts/atlas/locale-audit.json",
  }),
  Object.freeze({
    familyId: "basil-license-header",
    parentTaskDomain: "licensing",
    subjectEn: "Basil source-header policy",
    subjectZh: "Basil 源码头部策略",
    stableKeyEn: "generated-file treatment",
    stableKeyZh: "生成文件处理方式",
    stableValue: "exclude-generated-files",
    settingNameEn: "SPDX identifier",
    settingNameZh: "SPDX 标识",
    oldValue: "GPL-2.0-only",
    currentValue: "MIT",
    companionNameEn: "copyright year mode",
    companionNameZh: "版权年份模式",
    companionValue: "first-year-only",
    toolOutcomeEn: "the header scanner reported zero policy violations across 312 source files",
    toolOutcomeZh: "头部扫描器检查 312 个源码文件后报告零违规",
    workflowEn: "scan tracked handwritten sources and exclude generated clients before applying headers",
    workflowZh: "扫描受跟踪的手写源码，并在应用头部前排除生成客户端",
    gotchaEn: "Vendored notices remain untouched even when their syntax resembles project headers.",
    gotchaZh: "第三方 notice 即使格式相似也不能被项目头部改写",
    absentFieldEn: "manual exception approver",
    absentFieldZh: "手工例外审批人",
    filteredValue: "legal-review-amber",
    artifactRef: "artifacts/basil/header-scan.json",
  }),
  Object.freeze({
    familyId: "coral-client-generator",
    parentTaskDomain: "code-generation",
    subjectEn: "Coral API client generation",
    subjectZh: "Coral API 客户端生成",
    stableKeyEn: "schema pinning mode",
    stableKeyZh: "Schema 固定方式",
    stableValue: "checksum-and-version",
    settingNameEn: "generator release",
    settingNameZh: "生成器版本",
    oldValue: "2.3.1",
    currentValue: "2.4.0",
    companionNameEn: "endpoint ordering",
    companionNameZh: "端点排序",
    companionValue: "path-then-method",
    toolOutcomeEn: "the regenerated client matched all 17 expected endpoint signatures",
    toolOutcomeZh: "重新生成的客户端与 17 个预期端点签名全部一致",
    workflowEn: "verify the schema checksum, generate into a temporary tree, then compare signatures",
    workflowZh: "先验证 Schema 校验和，在临时目录生成，再比较端点签名",
    gotchaEn: "A version match without a checksum match is not accepted.",
    gotchaZh: "只有版本一致但校验和不一致时仍不得接受",
    absentFieldEn: "manual SDK release owner",
    absentFieldZh: "SDK 手工发布负责人",
    filteredValue: "sdk-operator-cyan",
    artifactRef: "artifacts/coral/client-signatures.json",
  }),
  Object.freeze({
    familyId: "denim-container-uid",
    parentTaskDomain: "containers",
    subjectEn: "Denim worker container",
    subjectZh: "Denim Worker 容器",
    stableKeyEn: "writable output path",
    stableKeyZh: "可写输出路径",
    stableValue: "/workspace/out",
    settingNameEn: "runtime UID",
    settingNameZh: "运行时 UID",
    oldValue: "1000",
    currentValue: "65532",
    companionNameEn: "root filesystem mode",
    companionNameZh: "根文件系统模式",
    companionValue: "read-only",
    toolOutcomeEn: "the non-root smoke wrote only to the declared output mount and exited cleanly",
    toolOutcomeZh: "非 root smoke 只写入声明的输出挂载点并正常退出",
    workflowEn: "start with a read-only root, mount the output directory, then run the ownership probe",
    workflowZh: "使用只读根文件系统启动，挂载输出目录，再运行所有权探针",
    gotchaEn: "The package cache is not a writable runtime escape hatch.",
    gotchaZh: "包缓存不能作为运行时可写逃生口",
    absentFieldEn: "break-glass root operator",
    absentFieldZh: "紧急 root 操作人",
    filteredValue: "ops-indigo",
    artifactRef: "artifacts/denim/non-root-smoke.json",
  }),
  Object.freeze({
    familyId: "elm-pool-ceiling",
    parentTaskDomain: "database-runtime",
    subjectEn: "Elm database connection pool",
    subjectZh: "Elm 数据库连接池",
    stableKeyEn: "idle timeout",
    stableKeyZh: "空闲超时",
    stableValue: "45s",
    settingNameEn: "maximum open connections",
    settingNameZh: "最大连接数",
    oldValue: "32",
    currentValue: "12",
    companionNameEn: "minimum idle connections",
    companionNameZh: "最小空闲连接数",
    companionValue: "2",
    toolOutcomeEn: "the saturation run completed without starvation at the twelve-connection ceiling",
    toolOutcomeZh: "饱和测试在 12 连接上限下完成且没有饥饿",
    workflowEn: "warm two idle connections, apply the ceiling, then run the bounded saturation probe",
    workflowZh: "预热两个空闲连接，应用上限，再运行有界饱和探针",
    gotchaEn: "Background migrations must use the same pool instead of opening an unbounded side channel.",
    gotchaZh: "后台迁移必须复用同一连接池，不能另开无界通道",
    absentFieldEn: "after-hours database caller",
    absentFieldZh: "非工作时间数据库联系人",
    filteredValue: "dba-violet",
    artifactRef: "artifacts/elm/pool-saturation.json",
  }),
  Object.freeze({
    familyId: "fable-alpha-mode",
    parentTaskDomain: "image-pipeline",
    subjectEn: "Fable image import pipeline",
    subjectZh: "Fable 图片导入流水线",
    stableKeyEn: "sampling filter",
    stableKeyZh: "采样过滤器",
    stableValue: "nearest-neighbor",
    settingNameEn: "alpha representation",
    settingNameZh: "Alpha 表示方式",
    oldValue: "straight-alpha",
    currentValue: "premultiplied-alpha",
    companionNameEn: "color space",
    companionNameZh: "色彩空间",
    companionValue: "sRGB",
    toolOutcomeEn: "the edge-pixel comparison found no dark fringe on all twelve reference sprites",
    toolOutcomeZh: "边缘像素比较确认 12 张参考精灵均无黑边",
    workflowEn: "premultiply during import, preserve sRGB metadata, then compare edge pixels",
    workflowZh: "导入时预乘 Alpha，保留 sRGB 元数据，再比较边缘像素",
    gotchaEn: "A healthy source PNG does not prove the runtime consumer uses the same alpha mode.",
    gotchaZh: "源 PNG 正常不能证明运行时消费者采用相同 Alpha 模式",
    absentFieldEn: "manual art override owner",
    absentFieldZh: "美术手工覆盖负责人",
    filteredValue: "art-pink",
    artifactRef: "artifacts/fable/edge-pixels.json",
  }),
]);

export const calibrationScenarioSeeds: readonly SharedScenarioSeed[] = Object.freeze([
  Object.freeze({
    familyId: "glacier-audio-rate",
    parentTaskDomain: "audio-pipeline",
    subjectEn: "Glacier audio import",
    subjectZh: "Glacier 音频导入",
    stableKeyEn: "channel policy",
    stableKeyZh: "声道策略",
    stableValue: "preserve-stereo",
    settingNameEn: "project sample rate",
    settingNameZh: "项目采样率",
    oldValue: "44100Hz",
    currentValue: "48000Hz",
    companionNameEn: "normalization mode",
    companionNameZh: "归一化模式",
    companionValue: "peak-disabled",
    toolOutcomeEn: "the ten-minute alignment probe ended with zero measurable timeline drift",
    toolOutcomeZh: "十分钟对齐探针结束时没有测得时间轴漂移",
    workflowEn: "decode at source rate, resample once to 48kHz, then run the alignment probe",
    workflowZh: "按源采样率解码，只重采样一次到 48kHz，再运行对齐探针",
    gotchaEn: "Metadata equality alone does not establish audible continuity.",
    gotchaZh: "元数据一致本身不能证明听感连续",
    absentFieldEn: "emergency mastering contact",
    absentFieldZh: "紧急母带联系人",
    filteredValue: "audio-silver",
    artifactRef: "artifacts/glacier/alignment.json",
  }),
  Object.freeze({
    familyId: "hazel-test-shards",
    parentTaskDomain: "test-orchestration",
    subjectEn: "Hazel test shard allocation",
    subjectZh: "Hazel 测试分片分配",
    stableKeyEn: "allocation key",
    stableKeyZh: "分配键",
    stableValue: "stable-test-id",
    settingNameEn: "shard count",
    settingNameZh: "分片数量",
    oldValue: "4",
    currentValue: "6",
    companionNameEn: "retry placement",
    companionNameZh: "重试位置",
    companionValue: "same-shard",
    toolOutcomeEn: "the six-shard replay stayed within eight percent duration skew",
    toolOutcomeZh: "六分片回放的耗时偏差保持在 8% 以内",
    workflowEn: "sort by stable test ID, assign six shards, and keep retries on their original shard",
    workflowZh: "按稳定测试 ID 排序，分配六个分片，并让重试留在原分片",
    gotchaEn: "Wall-clock discovery order must not affect shard membership.",
    gotchaZh: "测试发现的墙钟顺序不能影响分片归属",
    absentFieldEn: "manual flaky-test dispatcher",
    absentFieldZh: "手工不稳定测试调度人",
    filteredValue: "qa-gold",
    artifactRef: "artifacts/hazel/shard-replay.json",
  }),
  Object.freeze({
    familyId: "ivory-cli-schema",
    parentTaskDomain: "cli-contract",
    subjectEn: "Ivory CLI output contract",
    subjectZh: "Ivory CLI 输出合同",
    stableKeyEn: "error stream",
    stableKeyZh: "错误输出流",
    stableValue: "stderr",
    settingNameEn: "machine output schema",
    settingNameZh: "机器输出 Schema",
    oldValue: "text-v1",
    currentValue: "json-v2",
    companionNameEn: "success exit code",
    companionNameZh: "成功退出码",
    companionValue: "0",
    toolOutcomeEn: "the compatibility probe parsed every v2 response without fallback text",
    toolOutcomeZh: "兼容探针解析了全部 v2 响应且没有回退文本",
    workflowEn: "request JSON v2, validate the strict schema, and keep diagnostics on stderr",
    workflowZh: "请求 JSON v2，执行严格 Schema 校验，并把诊断保留在 stderr",
    gotchaEn: "Human-readable banners are forbidden in machine mode.",
    gotchaZh: "机器模式禁止出现面向人的 banner",
    absentFieldEn: "manual schema waiver owner",
    absentFieldZh: "Schema 手工豁免负责人",
    filteredValue: "cli-orange",
    artifactRef: "artifacts/ivory/cli-contract.json",
  }),
  Object.freeze({
    familyId: "jade-cors-origins",
    parentTaskDomain: "web-security",
    subjectEn: "Jade browser origin policy",
    subjectZh: "Jade 浏览器 Origin 策略",
    stableKeyEn: "credential mode",
    stableKeyZh: "凭证模式",
    stableValue: "credentials-enabled",
    settingNameEn: "allowed origin rule",
    settingNameZh: "允许 Origin 规则",
    oldValue: "wildcard",
    currentValue: "exact-app-origin",
    companionNameEn: "preflight cache duration",
    companionNameZh: "预检缓存时长",
    companionValue: "600s",
    toolOutcomeEn: "the signed-in browser preflight passed and an unlisted origin was rejected",
    toolOutcomeZh: "登录态浏览器预检通过，未列出的 Origin 被拒绝",
    workflowEn: "match the exact application origin, include credentials, then test one denied origin",
    workflowZh: "匹配精确应用 Origin，携带凭证，再测试一个被拒绝的 Origin",
    gotchaEn: "Wildcard origins cannot be combined with credentialed requests.",
    gotchaZh: "通配 Origin 不能与带凭证请求组合",
    absentFieldEn: "temporary origin exception owner",
    absentFieldZh: "临时 Origin 例外负责人",
    filteredValue: "web-green",
    artifactRef: "artifacts/jade/cors-preflight.json",
  }),
  Object.freeze({
    familyId: "koala-signing-profile",
    parentTaskDomain: "release-signing",
    subjectEn: "Koala desktop signing",
    subjectZh: "Koala 桌面签名",
    stableKeyEn: "target architecture",
    stableKeyZh: "目标架构",
    stableValue: "arm64",
    settingNameEn: "signing profile",
    settingNameZh: "签名配置",
    oldValue: "development",
    currentValue: "distribution",
    companionNameEn: "timestamp service",
    companionNameZh: "时间戳服务",
    companionValue: "required",
    toolOutcomeEn: "the notarization service accepted the distribution-signed arm64 bundle",
    toolOutcomeZh: "公证服务接受了 distribution 签名的 arm64 包",
    workflowEn: "build arm64, sign with the distribution profile, timestamp, then submit for notarization",
    workflowZh: "构建 arm64，使用 distribution 配置签名并加时间戳，再提交公证",
    gotchaEn: "A local signature check does not replace the notarization result.",
    gotchaZh: "本地签名检查不能替代公证结果",
    absentFieldEn: "emergency certificate custodian",
    absentFieldZh: "紧急证书保管人",
    filteredValue: "release-blue",
    artifactRef: "artifacts/koala/notarization.json",
  }),
  Object.freeze({
    familyId: "linen-log-redaction",
    parentTaskDomain: "observability-security",
    subjectEn: "Linen structured logging",
    subjectZh: "Linen 结构化日志",
    stableKeyEn: "request identifier treatment",
    stableKeyZh: "请求标识处理",
    stableValue: "stable-hash",
    settingNameEn: "redaction field set",
    settingNameZh: "脱敏字段集合",
    oldValue: "password-only",
    currentValue: "token-cookie-authorization",
    companionNameEn: "payload body policy",
    companionNameZh: "请求体策略",
    companionValue: "deny-by-default",
    toolOutcomeEn: "the seeded-secret scan found zero raw credentials in 20,000 log events",
    toolOutcomeZh: "种子 Secret 扫描在两万条日志事件中发现零个原始凭证",
    workflowEn: "redact the configured fields before serialization, hash request IDs, then scan seeded logs",
    workflowZh: "序列化前脱敏配置字段，对请求 ID 做哈希，再扫描带种子的日志",
    gotchaEn: "Redaction after serialization can leave copies inside nested error objects.",
    gotchaZh: "序列化后再脱敏可能在嵌套错误对象里留下副本",
    absentFieldEn: "manual log disclosure approver",
    absentFieldZh: "日志手工披露审批人",
    filteredValue: "security-red",
    artifactRef: "artifacts/linen/secret-scan.json",
  }),
]);

